language: node_js

node_js:
  - "lts/*"

cache: npm

git:
  depth: false

before_script:
  - npm install

script:
  - npm run check
  - npm run test
  - npm run build
  # @TODO remove next command and `publishConfig` field in package.json when publishing as a public package in NPM registry
  - if [[ $TRAVIS_BRANCH == "travis_config" && $TRAVIS_EVENT_TYPE != "pull_request" ]]; then echo "publishing" ; curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} https://splitio.jfrog.io/artifactory/api/npm/auth >> ~/.npmrc ; npm publish --tag rc ; else echo "no publishing" ; fi
