language: node_js

node_js:
  - "lts/*"

cache: npm

git:
  depth: false

before_script:
  - npm install

script:
  - npm run check
  - npm run test
  - npm run build
  - curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} https://splitio.jfrog.io/artifactory/api/npm/auth >> ~/.npmrc

jobs:
  include:
    - stage: publish
      script:
        - npm publish --tag rc

stages:
  - name: publish
    if: (branch = travis_config) AND NOT (type = pull_request)
